workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Set Java version
        script: |
          java -version
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/**/outputs/**/*.apk
